// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230319181125_UseDomainTypesInEF")]
    partial class UseDomainTypesInEF
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Infrastructure.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.UserEntity", b =>
                {
                    b.OwnsOne("Domain.HashedPassword", "HashedPassword", b1 =>
                        {
                            b1.Property<int>("UserEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.OwnsOne("Domain.ValidEmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("UserEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("HashedPassword")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
